name: RPBookGUI
version: 2.9.8
author: Puyodead1
main: io.github.puyodead1.rpbookgui.RPBookGUI
depend: [RandomPackage]
api-version: 1.13
commands:
  bookgui:
    description: Open the main menu
  rarityinfo:
    description: Get rarity of an enchant by name